import type { Metadata } from 'next'
import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { cn } from "@/lib/utils";
import './globals.css'
import { Toaster } from "@/components/ui/sonner";
import WalletconnectProvider from "@/providers/walletconnect-provider";
import { headers } from "next/headers"; // added
import { ReactQueryProvider } from '@/providers/react-query-provider';
import { SolanaProvider } from '@/providers/solana-provider';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();
  const cookies = headers().get('cookie')

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            inter.className
          )}>
          <ReactQueryProvider>
            <WalletconnectProvider cookies={cookies}>
              <SolanaProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  disableTransitionOnChange
                >
                  {children}
                  <Toaster />
                </ThemeProvider>
              </SolanaProvider>
            </WalletconnectProvider>
          </ReactQueryProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
